enabled_locales: ["en"]
static_pages:
  rails_contact: "http://www.railstutorial.org/contact"
  screencasts: "http://screencasts.railstutorial.org/"
  rails_help: "http://www.railstutorial.org/help"
  rails_book: "http://www.railstutorial.org/book"
  rails: "http://www.railstutorial.org/"
users:
  max_name: 50
  max_pass: 255
layouts:
  rails: "http://www.railstutorial.org/"
  news: "http://news.railstutorial.org/"
  michael: "http://www.michaelhartl.com/"
